NFT Airdrop init (merkletreejs)
hats-finance/hats pull request #57
Opened 2021-11-21 15:02 UTC by roienatan

2021-12-20 18:19 UTC, richardmands requested changes
Hi. Found one typo. All else seems fine.

2021-12-20 18:19 UTC, richardmands commented on src/components/Navigation/Menu.scss
> +  height: calc(100% - #{$header-hight});
should be 'header-height' I presume

2021-12-20 18:31 UTC, richardmands approved these changes

2021-12-21 15:49 UTC, roienatan commented
Merging but temporary disabling the option for the user to see it until we decided if further improvements and features are necessary. Comments related to that are under `NFT Airdrop - Temporary disabled` label in the code.

2021-12-21 15:52 UTC, merged