Decrypt tool
hats-finance/hats pull request #71
Opened 2022-01-12 18:24 UTC by leviyehonatan

A new tool to allow users to read messages sent from vurnability submitters,

This tool is a vault for pgp keys that is saved locally on the browser's store and is unlocked using a single password to allow to collect multiple keys for the ease of use of committee members to audit submitted bugs

2022-01-13 18:11 UTC, roienatan requested changes

2022-01-13 18:11 UTC, roienatan commented on src/components/CommitteeTools/CommitteTools.tsx
> +        <div>
The `<div>` is unnecessary here

2022-01-13 22:03 UTC, roienatan requested changes
As we implemented the support of i18next, we need for any new development to use it, also here.

2022-02-06 10:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hats-finance/hats?pullRequest=71) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/hats-finance/hats?pullRequest=71) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: roienatan<br/>:x: leviyehonatan<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hats-finance/hats?pullRequest=71) it.</sub>

2022-02-09 08:43 UTC, leviyehonatan reviewed
looks good

2022-02-09 08:49 UTC, leviyehonatan reviewed
looks good to me

2022-02-09 14:03 UTC, roienatan approved these changes

2022-02-09 14:03 UTC, merged